### ISSUE TITLE
Test value warning when `compute_test_value` is off

### ISSUE THREAD

**Issue by mattearllongshot** [aesara-devs/aesara#1021]
## Description of your problem or feature request

```python
import logging

import aesara
import aesara.tensor as at
import numpy as np

a = at.vector()
b = aesara.shared(np.zeros((0,)))

f = aesara.function([a], a + (a * b))

b.set_value(np.array([1,]))
print(f(np.array([3,])))
```

When running I get this warning:

```
WARNING (aesara.tensor.basic_opt): Cannot construct a scalar test value from a test value with no size: <TensorType(float64, (None,))>
```

However, computing test values is disabled:

```bash
$ python -c 'import aesara; print(aesara.config)' | grep -A3 '^compute_test_value\>'
compute_test_value ({'ignore', 'warn', 'off', 'raise', 'pdb'})
    Doc:  If 'True', Aesara will run each op at graph build time, using Constants, SharedVariables and the tag 'test_value' as inputs to the function. This helps the user track down problems in the graph before it gets optimized.
    Value:  off
```

## Versions and main components

* Aesara version: 2.5.1
* Aesara config (`python -c "import aesara; print(aesara.config)"`) 
[aesara_config.txt](https://github.com/aesara-devs/aesara/files/9019091/aesara_config.txt)

* Python version: Python 3.8.13
* Operating system: Ubuntu 18.04.6 LTS
* How did you install Aesara: conda

**Comment by mattearllongshot** [comment]
Just realised my aesara version is quite out of date, but I do also see it with 2.7.3 (conda).

**Comment by brandonwillard** [comment]
This bug is due to the legacy rewrite `aesara.tensor.basic_opt.local_elemwise_fusion_op`, which attempts to "fuse" sub-graphs containing only `Elemwise` `Op`s into a single `Elemwise` `Op`.

It quite controversially attempts to use test values to construct dummy inputs for the dummy `Op`s it constructs in order to determine whether or not C code can be generated for each `Op` in an `Elemwise`-only sub-graph.

In your case, this is the (sub-)graph it wants to fuse:
```python
import numpy as np
import aesara
import aesara.tensor as at


a = at.vector("a")
b = aesara.shared(np.zeros((0,)), name="b")

z = a + (a * b)

aesara.dprint(z)
# Elemwise{add,no_inplace} [id A]
#  |a [id B]
#  |Elemwise{mul,no_inplace} [id C]
#    |a [id B]
#    |b [id D]
```

While checking the `[id C]` node, it finds that `b` has a test value, because it's essentially a constant, and that value has zero dimensions.  For whatever reason, it decides that zero dimensions is bad and complains.

I'm not sure that such a warning/complaint is even useful in any way, so it should probably just be removed.  Ideally, this whole rewrite would be completely refactored, but we can save that for another time.

**Comment by mattearllongshot** [comment]
Excellent, thank you for taking a look.
