### ISSUE TITLE
Inconsistency in numba mode when passing scalar to function

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#1063]
In numba mode:
```python
import aesara
aesara.config.mode = "NUMBA"
import aesara.tensor as at

x = at.scalar(name="x")
f = aesara.function([x], 2*x)
print(repr(f(10)))  # prints 20.0
```

In c mode:

```python
import aesara
import aesara.tensor as at

x = at.scalar(name="x")
f = aesara.function([x], 2*x)
print(repr(f(10))) # prints array(20.)
```

This came up in https://github.com/pymc-devs/pymc/issues/5937. Found by [bherwerth](https://github.com/bherwerth).

**Comment by brandonwillard** [comment]
This is mostly due to Aesara's lack of support for built-in scalar types (e.g. `int`, `float`, etc.).  Every Aesara scalar is actually a NumPy `ndarray` scalar.

Since Numba supports the built-in scalar types and uses/returns them wherever/whenever it's reasonable, we face the challenge of deciding whether or not to manually convert all outputs to `ndarray`s within our Numba implementations, or let Numba use the built-in scalar types as much as possible and only construct `ndarray`s when it's necessary (e.g. when a Numba implementation expects/requires an `ndarray` input).

We've essentially chosen the latter, because it's cumulatively more efficient, since it produces Numba implementations with fewer `ndarray` constructions and allows the use of more performant scalars in some cases.

In this case, it looks like we might need to add another manual conversion somewhere, but, ideally, not the return value of our Numba implementations of `Elemwise` `Op`s.  Perhaps, it's possible for us to perform the conversion outside of Numba, or judiciously within Numba (e.g. applied only to the final outputs of a Numba-compiled graph).

**Comment by bherwerth** [comment]
If not touching the internals of the Numba implementation, how about applying `np.asarray` in the return statements in [`aesara.compile.function.types.Function.__call__`](https://github.com/aesara-devs/aesara/blob/58046078ec34bdb469f257d52b3e833b73b31b29/aesara/compile/function/types.py#L794)? 

In the docstring, one could then also specify the return type as `List[ndarray]`:

https://github.com/aesara-devs/aesara/blob/58046078ec34bdb469f257d52b3e833b73b31b29/aesara/compile/function/types.py#L816-L820

Btw, I noticed the docstring says the return type is `list`, but there seem to be `dict`s returned in some cases:

https://github.com/aesara-devs/aesara/blob/58046078ec34bdb469f257d52b3e833b73b31b29/aesara/compile/function/types.py#L1067-L1073

**Comment by brandonwillard** [comment]
> If not touching the internals of the Numba implementation, how about applying `np.asarray` in the return statements in [`aesara.compile.function.types.Function.__call__`](https://github.com/aesara-devs/aesara/blob/58046078ec34bdb469f257d52b3e833b73b31b29/aesara/compile/function/types.py#L794)?

That's what I would consider performing the conversion outside of Numba, and I'm very hesitant to take such an approach, mostly because of the way it mixes concerns/contexts.  The code in `Function` is supposed to handle the general use/orchestration of `VM`s, and the assumption is that a `VM` will produce valid outputs.  Adding a conversion step to `Function` mixes the responsibilities.

Moving further up the chain, even the `VM` assumes that the values put in its output storage `list`s are valid, so I think the right approach involves adding a `numpy.asarray` to the outputs somewhere after the call to `fgraph_to_python` in `aesara.link.numba.linker.NumbaLinker`.  The most direct place would probably be here: 
https://github.com/aesara-devs/aesara/blob/c8908e5a27ae34d16bc3c025424a77ac0268ac51/aesara/link/basic.py#L666-L673

Since this code is in a base class (i.e. `JITLinker`), we would need to consider whether or not the addition of `numpy.asarray` is appropriate in all cases.  My first thought is that it generally is.

N.B. We can't use `numpy.asarray` alone; instead, we would need to use `numpy.asarray(x, dtype=o_node.outputs[i].dtype)` in order to makes sure that the dtype of the converted scalar matches the graph's specification.

**Comment by brandonwillard** [comment]
> Btw, I noticed the docstring says the return type is `list`, but there seem to be `dict`s returned in some cases:

Yeah, we haven't started typing that module yet.  It's important that we start doing that work, though.
