### ISSUE TITLE
Function profiling should use `time.time_ns` instead of `time.time`

### ISSUE THREAD

**Issue by michaelosthege** [aesara-devs/aesara#1246]
## Description of your problem or feature request

The function profiling in https://github.com/aesara-devs/aesara/blob/2dc0af2f921e9d8795f270c0ec7a294c0b49a0be/aesara/compile/function/types.py#L827 (and more lines that file) uses `time.time()` which has varying precision on different platforms.

`time.time_ns()` or `time.time_ns() / (10 ** 9)` for float seconds should be used for high-precision performance measurement.

Further reading: https://stackoverflow.com/a/1938096

## Versions and main components

* Aesara version: 2.8.7
* Operating system: mac-OS, Windows

**Comment by brandonwillard** [comment]
Isn't [`time.perf_counter`](https://docs.python.org/3.5/library/time.html#time.perf_counter) provided explicitly for these purposes?

**Comment by anirudhacharya** [comment]
@brandonwillard yes, since we are only using it to measure time difference and nowhere are we logging the actual time of an event, `time.perf_counter()` makes more sense than `time.time()`.

Depending on how we want to do the profiling, the options are -
1. `time.time()`
2. `time.perf_counter()` - can be used to record the difference in clock time.
3. `time.process_time()` - can be used to record the difference in process time.

```python
import time

def perf_count():
    tic = time.perf_counter()
    time.sleep(1)
    toc = time.perf_counter()
    return toc - tic

def proc_time():
    tic = time.process_time()
    time.sleep(1)
    toc = time.process_time()
    return toc - tic

print(perf_count())
print(proc_time())
```
```
Output 
-------
1.003998823
5.9000000000003494e-05
```

Should I go ahead and change it to `perf_counter`?

**Comment by brandonwillard** [comment]
> Should I go ahead and change it to `perf_counter`?

Yes, that sounds good.
