### ISSUE TITLE
Add JAX Op for wrapping user-defined JAX functions

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#314]
@dfm has built this cool wrapper that allows JAX functions to be turned into Aesara Ops easily:
https://gist.github.com/dfm/a2db466f46ab931947882b08b2f21558

This would be a great feature to include as PyMC3 users could add arbitrary deterministics coded in JAX to their PyMC3 model.

Proposing to add this to the library.

**Comment by dfm** [comment]
It might be better to just add something like this to the docs rather than trying to support a feature since I expect it would be hard to do shape and dtype inference in a general non-kludgey way. Also: it would probably be good to add a grad method using the vjp, but I didn't work that through yet.

**Comment by brandonwillard** [comment]
> This would be a great feature to include as PyMC3 users could add arbitrary deterministics coded in JAX to their PyMC3 model.

I'm not aware of any JAX issues involving PyMC3 `Deterministic`s.  As far as I can tell, they should've always been supported via the standard Aesara-to-JAX conversion process.

Also, that example in the Gist isn't a single function that converts JAX functions to `Op`s, so it can't really serve as a new utility function of any sort.

More importantly, this isn't the kind of approach to `Op` creation that we want to promote, because&mdash;as @dfm mentioned&mdash;there are a lot of important things to consider and quite a few ways in which this could go wrong.  

For instance, is every JAX function completely NumPy compatible (i.e. always takes and returns NumPy-compatible arrays)?  If any return nested `list`s, a `tuple`, `dict`, etc., those would likely result in some very cryptic errors.  Do we need to be concerned about views on data: e.g. does JAX take and/or return array views in a consistent way, or does it always make copies?  These sorts of things could subtlety ruin performance or break things completely.

**Comment by brandonwillard** [comment]
FYI: this is also the exact same approach described [here](https://github.com/pymc-devs/pymc3/issues/4142#issuecomment-703293904), where it was given as a means of using shared variables with the NumPyro JAX sampler code.

[I followed up somewhat recently](https://github.com/pymc-devs/pymc3/issues/4142#issuecomment-786976626) to clarify that the `Op.perform` part of this approach is unimportant/undesirable, and that&mdash;in these rare cases&mdash;it's probably better to raise a `NotImplementedError` so that people won't mistakenly use these `Op`s when they're not compiling to JAX.

Overall, this is a decent way to include arbitrary JAX code into the JAX conversion process, but, without putting special attention into the `Op` implementation, it could result in some really poor `Op`s that shouldn't be used in any other scenario.

**Comment by twiecki** [comment]
@brandonwillard I agree that we need something like this so that JAX code can interact with Theano `Op`s. What do you mean however, special attention? I.e. what would need to be added here to make it better?

Also as for grads: shouldn't these come automatically from the JAX autodiff? I don't think we need our own grads for JAX anyway so this should already work for this Op.

**Comment by brandonwillard** [comment]
> ...we need something like this so that JAX code can interact with Theano `Op`s.

I'm saying that we might need to occasionally use this approach as a one-off to include arbitrary JAX expressions into JAX-ified Aesara graphs, but, outside of that context, we really shouldn't create `Op`s for JAX functions.

**Comment by twiecki** [comment]
I think this would be a super nice feature for users who have custom JAX code and want to use it with their pymc3 model. The same for custom distributions. Seems like this Op would make that pretty straight forward.

**Comment by zaxtax** [comment]
Do we still want this feature? Are there settings where we want the user writing JAX directly vs using aesara?

**Comment by twiecki** [comment]
Yeah, I think as user-facing this could be very useful. Alternatively we could place it into PyMC.

We write JAX-only custom Ops all the time at labs.

**Comment by brandonwillard** [comment]
Just like we originally did in PyMC for `Distribution`s, we can always automate the creation of dispatch functions during the construction of an `Op` (e.g. within `__new__` based on method/function names), but doing this at the type level is not the best approach (i.e. via a compilation target-specific type like a `JaxOp`).

**Comment by zaxtax** [comment]
I think the challenge is what if you want to do something that doesn't have or is unlikely to have an Op in aesara? Otherwise, I'm more sympathetic to the approach I think Brandon is espousing where users can define a custom op and pass a compilation target-specific dispatch function.

**Comment by rlouf** [comment]
Can we close this as _Not Planned_?
