### ISSUE TITLE
Make frequently used types available at the `aesara.*` level

### ISSUE THREAD

**Issue by michaelosthege** [aesara-devs/aesara#527]
Here's a list of submodules/types/functions that currently need their own import lines, but are so frequently used that I think we should aggregate them at higher package/submodule levels:

```python
from aesara.graph.basic import Constant, Variable
from aesara.tensor.var import TensorVariable
from aesara.compile.sharedvalue import SharedVariable
from aesara.tensor.sharedvar import ScalarSharedVariable
from aesara.graph.op import Op

import aesara.tensor as at
import aesara.tensor.random.basic as atr
```

While the above is not something I'd like to show others when demoing Aesara, this looks much less frightening:

```python
from aesara import Constant, Variable, TensorVariable, SharedVariable, ScalarSharedVariable, Op
import aesara.tensor as at
import aesara.tensor.random as atr
```

or simply this and rolling with `aesara.TensorVariable` and so on:

```python
import aesara
import aesara.tensor as at
import aesara.tensor.random as atr
```

Grouping the most important types at the package level also doesn't require in-depth knowledge of the codebase just to import things for an `isinstance` check.

Any concerns, or more things to add to the list?

@ricardoV94 @brandonwillard can someone add labels, please? I seem to have absolutely no permissions on this project any more :(

**Comment by brandonwillard** [comment]
Some of the basic classes could be exposed at higher package levels, but not all (e.g. it makes little-to-no sense to expose the `*SharedVariable` classes) and definitely not at the highest package level (i.e. `aesara`), as your examples do.  

One of the most fundamental deciding factors is whether or not a class is intended to be used directly, and none of the classes in your example fit that simple criteria.

Other reasonable considerations involve the types of operations user-level code would be expected to do with Aesara objects, and these needs to be considered with the following question in mind: "Are we still talking about _users_, or are we now talking about _developers_?".

While ease-of-`isinstance`-use may _seem_ like one, it can easily devolve into a justification for exposing everything at the top level, so that's not good enough.  At most, `Variable` could be at the top level and `TensorVariable` at `aesara.tensor`.  That's enough to address most reasonable `isinstance` cases.


> While the above is not something I'd like to show others when demoing Aesara, this looks much less frightening:
> ...
> Grouping the most important types at the package level also doesn't require in-depth knowledge of the codebase just to import things for an `isinstance` check.

These are specious points/arguments.  The first one is simply FUD, and it's not welcome here.  I'm assuming the second is hyperbole, because, when one considers the circumstances under which a user would even determine that they need `TensorVariable` in the first place, the claim makes no sense.  (For example, if they used `type(...)` at any point, then they know **exactly** where the class is.)
