### ISSUE TITLE
Add a JAX conversion for `Assert` `Op`s

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#629]
https://github.com/pymc-devs/pymc/blob/8a72d37bacfcac0804a74207088bd5d58a0ea495/pymc/sampling_jax.py#L34-L43

**Comment by kc611** [comment]
Yes that will definitely work. 

Something like:

```python
from aesara.raise_op import CheckAndRaise

@jax_funcify.register(CheckAndRaise)
def jax_funcify_Assert(op, **kwargs):
    def assert_fn(value, *inps):
        if not jnp.all(*inps):
            raise ValueError("Check failed: " + op.msg)
        return value

    return assert_fn

```
(Tested in on above presented code)

I feel kinda stupid why I didn't think of this before back when we faced the same problem in PyMC.

**Comment by rlouf** [comment]
Alright, should I add the `Assert` Op in the link at the top of this thread as well?

**Comment by kc611** [comment]
Ah, no need for that. 

If we implement https://github.com/aesara-devs/aesara/issues/629#issuecomment-1027007347 in Aesara, we could in fact remove that Assert from PyMC as well. Since `Assert` is simply a subclass of `CheckAndRaise` with only change being the type of error that's being raised.

**Comment by rlouf** [comment]
There is something I did not think about and just realized while testing the new conversion. The following function:

```python
import jax

def fn(x):
    if x < 0:
        return 1
    return x

f = jax.jit(fn)
f(-1)
```

will raise a `ConcretizationTypeError`, thus the same happens with the `jax_funcify_Assert` conversion above.

**Comment by rlouf** [comment]
I'm reopening this as I feel failing explicitly when there is an assert is way more conservative than we need to be. People use JAX at their own risk; unless we are able to determine the `Assert` won't succeed at compilation time there's no reason we should impose constraints that otherwise don't exist in the target language.

What feels more appropriate imo would be to add python `assert` statements and return a non-jitted function to the user.
