### ISSUE TITLE
Bug in `squeeze` when using negative `axis`

### ISSUE THREAD

**Issue by ricardoV94** [aesara-devs/aesara#830]
Squeeze does not seem to do anything when axis is negative:
```python
import aesara.tensor as at
at.squeeze(at.as_tensor_variable([1]), axis=-1).eval()
# array([1])
at.squeeze(at.as_tensor_variable([[1]]), axis=-1).eval()
# array([[1]])
```
This doesn't happen with positive axis:
```python
at.squeeze(at.as_tensor_variable([1]), axis=0).eval()
# array(1)
at.squeeze(at.as_tensor_variable([[1]]), axis=0).eval()
# array([1])
```

**Comment by kc611** [comment]
Looks like `at.squeeze` logic doesn't account for negative axes:

https://github.com/aesara-devs/aesara/blob/7e351b93288447db958a6919bbe22efe9889d6ce/aesara/tensor/extra_ops.py#L620 

Could be fixed by simply adding an conditional statement before this logic to convert the negative axis into a normal positive one. i.e. 
```python
if axis < 0: 
   axis = axis + x.ndim
```

**Comment by ricardoV94** [comment]
Hmm that could also seems to silence incorrect use of squeeze (if you try to squeeze a non broadcastable dimension)
