### ISSUE TITLE
Add JAX implementation for `BroadcastTo`

### ISSUE THREAD

**Issue by twiecki** [aesara-devs/aesara#859]
Seems like `BroadcastTo` has no JAX implementation: https://github.com/pymc-devs/pymc/issues/5468#issuecomment-1056041513

**Comment by ricardoV94** [comment]
I added a tentative wontfix because the plan is to remove this Op altogether, once https://github.com/aesara-devs/aesara/pull/825 is sorted out

**Comment by ricardoV94** [comment]
Apologies, I confused it with `Rebroadcast`, this one needs to be added yes

**Comment by twiecki** [comment]
Docs on how to add it: https://aesara.readthedocs.io/en/latest/extending/creating_a_numba_jax_op.html

**Comment by danhphan** [comment]
Hi team, pls let me work on this one. 

There seems already a relevant JAX method [`jax.numpy.broadcast_to`](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.broadcast_to.html)

Thanks.

**Comment by danhphan** [comment]
Hi, I have implemented the Jax version of BroadcastTo, and add `test_BroadcastTo` tests into `test_jax.py` in my local machine. 
However, when running the Jax  `test_BroadcastTo` tests (similar to `test_BroadcastTo` in [test_numba.py](https://github.com/aesara-devs/aesara/blob/e60cfb57d45663f36ee6010ad18829322d373a30/tests/link/test_numba.py#L1933)), some tests passed, while some tests failed.

I debugged the code, and saw that the tests will **pass** if input `shape` is aesara `TensorConstant`:
```
shape in test_BroadcastTo: [TensorConstant{3}, TensorConstant{2}]
shape in jax_funcify_BroadcastTo: (DeviceArray(3, dtype=int64), DeviceArray(2, dtype=int64))
```

And the tests will **fail** if input `shape` is aesara `TensorVariable`
```
shape in test_BroadcastTo: [<TensorType(int64, ())>, <TensorType(int64, ())>]
shape in jax_funcify_BroadcastTo: (Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=0/1)>, Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=0/1)>)
```
##### Error:
`TypeError: Shapes must be 1D sequences of concrete values of integer type, got (Traced<ShapedArray(int64[])...`

This is because, [jax.numpy.broadcast_to(arr, shape)](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.broadcast_to.html) only accept `shape` as a **static variable** like `DeviceArray` (not a traced variable).

I have tried using `@jax.jit` `static_argnums` to  `@jax.jit(broadcast_to, static_argnums=(1,))`, but this not work.

Now I am thinking to create a `new_shape` (aesara `TensorConstant`) from `shape` (aesara `TensorVarialbe`), and pass it to `jax.numpy.broadcast_to(arr, shape)`. But not sure how to do it.

Any suggestions to bypass or convert `shape` into **static variable** for `jax.numpy.broadcast_to(arr, shape)`?

This is the current implementation. Thank you.

#### In jax/dispatch.py
```
@jax_funcify.register(BroadcastTo)
def jax_funcify_BroadcastTo(op, node, **kwargs):   test_BroadcastTo

    def broadcast_to(x, *shape):
        return jnp.broadcast_to(x, shape) # This only accepts shape as a static variable

    return broadcast_to # Already try: return @jax.jit(broadcast_to, static_argnums=(1,)), but this not work
```

#### In link/test_jax.py
```
@pytest.mark.parametrize(
    "x, shape",
    [
        (
            set_test_value(vector("x"), np.random.random(size=(2,)).astype(config.floatX)),
            [set_test_value(lscalar(), np.array(v)) for v in [3, 2]],
        ),
        (
            set_test_value(vector("x"), np.random.random(size=(2,)).astype(config.floatX)),
            [at.as_tensor(3, dtype=np.int64), at.as_tensor(2, dtype=np.int64)],
        ),
    ],
)
def test_BroadcastTo(x, shape):
    out = at_extra_ops.broadcast_to(x, shape)
    fgraph = FunctionGraph(outputs=[out])    
    compare_jax_and_py(fgraph, [get_test_value(i) for i in fgraph.inputs])
```

**Comment by twiecki** [comment]
@danhphan Yes, JAX does not support dynamic shapes. I'm not quite sure what we settled on as the proper solution (@brandonwillard @ricardoV94 ?), but converting to static shape seems reasonable to me.

**Comment by ricardoV94** [comment]
There's no way around it as long as we are jitting everything when compiling to JAX. You can remove those conditions from the test as they are simply not supported when using Aesara+JAX at the moment.

https://github.com/aesara-devs/aesara/issues/684

**Comment by danhphan** [comment]
Hi yes, thanks both, I will remove these cases from the tests, and submit a PR soon :)
